version: '3.5'
services:
  # Запуск пустого экземпляра MariaDB сервера
  mysql-server:
    image: mariadb:10
    container_name: mysql-server
    env_file:
      - main.env
    volumes:
      - ./backup:/backup
    restart: always
    command: 
      --character-set-server=utf8 
      --collation-server=utf8_bin 
      --default-authentication-plugin=mysql_native_password 

  # Запуск экземпляра Zabbix Java gateway
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-5.0-latest
    container_name: zabbix-java-gateway
    restart: always

  # Запуск экземпляра Zabbix сервера и соединение этого экземпляра с недавно созданным экземпляром MariaDB сервера и Zabbix Java gateway
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    container_name: zabbix-server-mysql
    env_file:
      - main.env
    volumes:
      - ./zabbix/mibs:/var/lib/zabbix/mibs
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
    links:
      - mysql-server:mysql
      - zabbix-java-gateway:zabbix-java-gateway
    ports: 
      - 10051:10051
    restart: always

  # Запуск Zabbix веб-интерфейса и соединение этого экземпляра с недавно созданными экземплярами MariaDB сервера и Zabbix сервера
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
    container_name: zabbix-web-nginx-mysql
    env_file:
      - main.env
    links:
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    ports:
      - 32775:8080
    restart: always

  # Это сервисный контейнер для резервного копирования в котором работает cron, необходимые пакеты можно доустановить через dockerfile
  backup:
    build: .
    # Для использования готового образа hub.docker.com/repository/docker/batonogov/zabbix-backup
    # image: batonogov/zabbix-backup 
    container_name: zabbix-backup
    privileged: true
    links:
      - mysql-server
    env_file:
      - main.env
      # - secrets.env
    volumes:
      - ./backup:/backup
      - ./zabbix/mibs:/var/lib/zabbix/mibs
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./cron/hourly:/etc/cron.hourly
      - ./cron/daily:/etc/cron.daily
      - ./cron/weekly:/etc/cron.weekly
      - ./cron/monthly:/etc/cron.monthly
      - ./cron/reboot:/etc/cron.reboot
      - ./cron/start:/etc/cron.start
      - ./cron/logs:/var/log/cron
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - 32776:3000
    env_file: 
      - grafana/configure.env
      - grafana/plugins.env
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana/
    restart: always
